'use strict';
const H=require('./_lib/http');
const db=require('./_lib/supabase');
const auth=require('./_lib/auth');
const C=require('./_lib/crypto');
const BufferAPI=require('./_lib/buffer');
const Mail=require('./_lib/email');

function q(v){return encodeURIComponent(v);}
function titleFromCaption(value){const clean=String(value||'').replace(/\s+/g,' ').trim();return clean?(clean.length>46?clean.slice(0,46).trim()+'…':clean):'Untitled Buffer post';}
function publicBase(event){return (process.env.APP_BASE_URL||((event.headers['x-forwarded-proto']||'https')+'://'+event.headers.host)).replace(/\/$/,'');}
function mapClient(row){let roomToken='',approvalCode='';try{roomToken=C.decrypt(row.room_token_ciphertext);}catch(e){}try{approvalCode=C.decrypt(row.approval_code_ciphertext);}catch(e){}return {id:row.id,name:row.contact_name,company:row.company,email:row.email,approvalOwner:row.approval_owner,approvalNote:row.approval_note||'',roomToken,approvalCode,color:row.color||'#cafd00',colorText:row.color_text||'#0d0f0c',initials:row.initials||'',active:row.active!==false};}
function mapItem(row){return {id:row.id,bufferId:row.buffer_post_id,clientId:row.client_id,title:row.title,caption:row.caption||'',image:row.image_url||'',platform:row.platform||'Buffer',service:row.service||'',channelId:row.channel_id||'',status:row.status||'draft',bufferStatus:row.buffer_status||'draft',dueAt:row.due_at,version:row.version||1,changedSinceReview:Boolean(row.changed_since_review),approvedBy:row.approved_by,approvedAt:row.approved_at,receiptCode:row.receipt_code,currentFingerprint:row.current_fingerprint,createdAt:row.source_created_at||row.created_at,updatedAt:row.updated_at};}
function mapComment(row){return {id:row.id,authorType:row.author_type,authorName:row.author_name,body:row.body,kind:row.kind,createdAt:row.created_at};}
function mapReceipt(row){return {id:row.id,receiptCode:row.receipt_code,postId:row.content_item_id,clientId:row.client_id,clientCompany:row.client_company,title:row.title,platform:row.platform,approverName:row.approver_name,approvedAt:row.approved_at,version:row.version,fingerprint:row.fingerprint,snapshot:row.snapshot_json||{}};}
async function ownItem(userId,id){return db.one('content_items','select=*&id=eq.'+q(id)+'&user_id=eq.'+q(userId));}
async function ownClient(userId,id){return db.one('clients','select=*&id=eq.'+q(id)+'&user_id=eq.'+q(userId));}
async function bootstrap(user){
  const [profiles,clients,items,receipts]=await Promise.all([
    db.select('profiles','select=*&id=eq.'+q(user.id)+'&limit=1'),
    db.select('clients','select=*&user_id=eq.'+q(user.id)+'&active=eq.true&order=created_at.asc'),
    db.select('content_items','select=*&user_id=eq.'+q(user.id)+'&archived=eq.false&order=updated_at.desc'),
    db.select('receipts','select=*&user_id=eq.'+q(user.id)+'&order=approved_at.desc')
  ]);
  const lastSync=(items||[]).map(x=>x.last_synced_at).filter(Boolean).sort().reverse()[0]||null;
  return {profile:{id:user.id,email:user.email||'',name:(profiles[0]&&profiles[0].display_name)||''},clients:(clients||[]).map(mapClient),posts:(items||[]).map(mapItem),receipts:(receipts||[]).map(mapReceipt),lastSync};
}
async function createClient(user,p){
  if(!p.company||!p.email||!(p.approvalOwner||p.name))throw Object.assign(new Error('Company, owner, and email are required.'),{statusCode:400});
  const token=C.randomToken(),code=C.ownerCode();
  const rows=await db.insert('clients',{user_id:user.id,company:String(p.company).trim(),contact_name:String(p.name||p.approvalOwner).trim(),email:String(p.email).trim(),approval_owner:String(p.approvalOwner||p.name).trim(),approval_note:String(p.approvalNote||'').trim(),room_token_hash:C.sha256(token),room_token_ciphertext:C.encrypt(token),approval_code_hash:C.sha256(code),approval_code_ciphertext:C.encrypt(code),color:p.color||'#cafd00',color_text:'#0d0f0c',initials:String(p.company).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()});
  return {client:mapClient(rows[0])};
}
async function rotateClientSecret(user,p){const client=await ownClient(user.id,p.clientId);if(!client)throw Object.assign(new Error('Client not found.'),{statusCode:404});if(p.kind==='room'){const token=C.randomToken();const rows=await db.update('clients','id=eq.'+q(client.id)+'&user_id=eq.'+q(user.id),{room_token_hash:C.sha256(token),room_token_ciphertext:C.encrypt(token),updated_at:new Date().toISOString()});return {client:mapClient(rows[0])};}const code=C.ownerCode();const rows=await db.update('clients','id=eq.'+q(client.id)+'&user_id=eq.'+q(user.id),{approval_code_hash:C.sha256(code),approval_code_ciphertext:C.encrypt(code),updated_at:new Date().toISOString()});return {client:mapClient(rows[0])};}
async function assignPost(user,p){const item=await ownItem(user.id,p.postId);if(!item)throw Object.assign(new Error('Post not found.'),{statusCode:404});if(p.clientId){const client=await ownClient(user.id,p.clientId);if(!client)throw Object.assign(new Error('Client not found.'),{statusCode:404});}const rows=await db.update('content_items','id=eq.'+q(item.id)+'&user_id=eq.'+q(user.id),{client_id:p.clientId||null,updated_at:new Date().toISOString()});return {post:mapItem(rows[0])};}
async function sendForReview(user,p){const item=await ownItem(user.id,p.postId);if(!item)throw Object.assign(new Error('Post not found.'),{statusCode:404});if(!item.client_id)throw Object.assign(new Error('Assign a client first.'),{statusCode:400});if(!item.latest_snapshot_id)throw Object.assign(new Error('This Buffer post has no snapshot yet. Sync again.'),{statusCode:400});const rows=await db.update('content_items','id=eq.'+q(item.id)+'&user_id=eq.'+q(user.id),{review_snapshot_id:item.latest_snapshot_id,status:'review',changed_since_review:false,feedback:null,approved_by:null,approved_at:null,receipt_code:null,updated_at:new Date().toISOString()});await db.insert('comments',{content_item_id:item.id,user_id:user.id,snapshot_id:item.latest_snapshot_id,author_type:'creator',author_name:user.email||'Creator',body:'Sent the latest Buffer snapshot for approval.',kind:'system'});return {post:mapItem(rows[0])};}
async function addCreatorComment(user,p){const item=await ownItem(user.id,p.postId);if(!item)throw Object.assign(new Error('Post not found.'),{statusCode:404});if(!String(p.body||'').trim())throw Object.assign(new Error('Comment cannot be empty.'),{statusCode:400});await db.insert('comments',{content_item_id:item.id,user_id:user.id,snapshot_id:item.review_snapshot_id||item.latest_snapshot_id,author_type:'creator',author_name:user.email||'Creator',body:String(p.body).trim(),kind:'comment'});return {ok:true};}
async function postDetail(user,p){const item=await ownItem(user.id,p.postId);if(!item)throw Object.assign(new Error('Post not found.'),{statusCode:404});const [client,comments]=await Promise.all([item.client_id?ownClient(user.id,item.client_id):Promise.resolve(null),db.select('comments','select=*&content_item_id=eq.'+q(item.id)+'&order=created_at.asc')]);return {post:mapItem(item),client:client?mapClient(client):null,comments:(comments||[]).map(mapComment)};}
function snapshotFromBuffer(post){return {bufferPostId:post.bufferId,caption:post.caption||'',imageUrl:post.image||'',assets:Array.isArray(post.assets)?post.assets:[],platform:post.platform||'Buffer',service:post.service||'',channelId:post.channelId||'',bufferStatus:post.bufferStatus||'draft',dueAt:post.dueAt||null};}
async function syncBuffer(user,event){const token=(event.headers['x-buffer-token']||event.headers['X-Buffer-Token']||process.env.BUFFER_API_KEY||process.env.BUFFER_TOKEN||'').trim();const pulled=await BufferAPI.getPosts(token);let added=0,updated=0,changed=0;for(const post of pulled.posts){const snap=snapshotFromBuffer(post),fp=C.fingerprint(snap);const existing=await db.one('content_items','select=*&user_id=eq.'+q(user.id)+'&buffer_post_id=eq.'+q(post.bufferId));if(!existing){const inserted=await db.insert('content_items',{user_id:user.id,buffer_post_id:post.bufferId,title:titleFromCaption(post.caption),caption:post.caption||'',image_url:post.image||'',platform:post.platform||'Buffer',service:post.service||'',channel_id:post.channelId||'',buffer_status:post.bufferStatus||'draft',due_at:post.dueAt||null,status:'draft',version:1,current_fingerprint:fp,source_created_at:post.createdAt||new Date().toISOString(),last_synced_at:new Date().toISOString()});const item=inserted[0];const snapshots=await db.insert('content_snapshots',{content_item_id:item.id,user_id:user.id,version:1,caption:snap.caption,image_url:snap.imageUrl,platform:snap.platform,service:snap.service,channel_id:snap.channelId,buffer_status:snap.bufferStatus,due_at:snap.dueAt,fingerprint:fp,snapshot_json:snap});await db.update('content_items','id=eq.'+q(item.id),{latest_snapshot_id:snapshots[0].id});added++;continue;}if(existing.current_fingerprint!==fp){const version=(existing.version||1)+1;const snapshots=await db.insert('content_snapshots',{content_item_id:existing.id,user_id:user.id,version,caption:snap.caption,image_url:snap.imageUrl,platform:snap.platform,service:snap.service,channel_id:snap.channelId,buffer_status:snap.bufferStatus,due_at:snap.dueAt,fingerprint:fp,snapshot_json:snap});const hadReview=Boolean(existing.review_snapshot_id);await db.update('content_items','id=eq.'+q(existing.id)+'&user_id=eq.'+q(user.id),{title:titleFromCaption(post.caption),caption:post.caption||'',image_url:post.image||'',platform:post.platform||'Buffer',service:post.service||'',channel_id:post.channelId||'',buffer_status:post.bufferStatus||'draft',due_at:post.dueAt||null,version,current_fingerprint:fp,latest_snapshot_id:snapshots[0].id,status:hadReview?'draft':existing.status,changed_since_review:hadReview,approved_by:null,approved_at:null,receipt_code:null,last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()});changed++;updated++;}else{await db.update('content_items','id=eq.'+q(existing.id)+'&user_id=eq.'+q(user.id),{buffer_status:post.bufferStatus||'draft',due_at:post.dueAt||null,last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()});updated++;}}
  return {added,updated,changed,organization:pulled.organization};
}
async function inviteClient(user,p,event){const client=await ownClient(user.id,p.clientId);if(!client)throw Object.assign(new Error('Client not found.'),{statusCode:404});const room=C.decrypt(client.room_token_ciphertext),code=C.decrypt(client.approval_code_ciphertext),url=publicBase(event)+'/review/'+encodeURIComponent(room);const result=await Mail.sendEmail({to:client.email,subject:'Your '+client.company+' approval room',html:'<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h1>Content is ready for review</h1><p>Open the approval room to comment, request changes, or stamp final approval.</p><p><a href="'+url+'" style="display:inline-block;background:#cafd00;color:#354600;padding:12px 18px;border-radius:999px;text-decoration:none;font-weight:700">Open approval room</a></p><p><strong>Owner code:</strong> '+code+'</p><p style="color:#777;font-size:12px">The team can comment. The code holder can grant final approval.</p></div>'});return Object.assign(result,{preview:'Approval room: '+url+'\nOwner code: '+code});}

exports.handler=async function(event){const opt=H.options(event);if(opt)return opt;if(event.httpMethod!=='POST')return H.json(405,{error:'POST required.'});try{const user=await auth.userFromEvent(event);const body=H.parse(event),action=body.action,p=body.payload||{};let out;if(action==='bootstrap')out=await bootstrap(user);else if(action==='createClient')out=await createClient(user,p);else if(action==='rotateClientSecret')out=await rotateClientSecret(user,p);else if(action==='assignPost')out=await assignPost(user,p);else if(action==='sendForReview')out=await sendForReview(user,p);else if(action==='addCreatorComment')out=await addCreatorComment(user,p);else if(action==='postDetail')out=await postDetail(user,p);else if(action==='syncBuffer')out=await syncBuffer(user,event);else if(action==='inviteClient')out=await inviteClient(user,p,event);else throw Object.assign(new Error('Unknown creator action.'),{statusCode:400});return H.json(200,out);}catch(e){return H.fail(e);}};
